### ISSUE TITLE
editor crash profile save corruption

### ISSUE THREAD

**Issue by Eclipse2025** [FromDarkHell/BL3SaveEditor#9]
so testing on profile save (thanks for reminding about backups!)
any edits done on profile save, for weapons level/mayhem mods or unlock room customizations and characters customizations.
    edit1: also crashes/corrupts for just opening and then saving with no changes made
crash the editor during save/save as
corrupt the profile.sav can cant reopen with this error.
       Error parsing save: 
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex

here is debug text:
  at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at IOTools.IOWrapper.ReadInt32() in J:\Coding Projecties\BL3SaveEditor\IOTools\IOWrapper.cs:line 399
   at BL3Tools.BL3Tools.LoadFileFromDisk(String filePath, Platform platform, Boolean bBackup) in J:\Coding Projecties\BL3SaveEditor\BL3Tools\BL3Tools.cs:line 62
   at BL3SaveEditor.MainWindow.OpenSave(String filePath, Platform platform) in J:\Coding Projecties\BL3SaveEditor\BL3SaveEditor\MainWindow.xaml.cs:line 337

**Comment by FullZetsu** [comment]
[profile_broke.zip](https://github.com/FromDarkHell/BL3SaveEditor/files/7324624/profile_broke.zip)
[profile_def.zip](https://github.com/FromDarkHell/BL3SaveEditor/files/7324626/profile_def.zip)
Here are my own unbroken and broken profile.sav files.

**Comment by FromDarkHell** [comment]
Fixed in release [1.1.0](https://github.com/FromDarkHell/BL3SaveEditor/releases/tag/v1.1.0).

As an explanation instead of just saying `lol fixed bye`, @FullZetsu (and I figure @Eclipse2025 too)'s profile contained an item that I can't properly save out after reading it in. Each item has an "inventory key" attached, and for ECHO themes, they don't really have an inventory key attached. So when it would try to save the ECHO theme item, it would just crash because it didn't have the key.

Now instead, it basically "backs up" all items, so if it can't save it (no inventory key), it'll use that backup instead. I was actually already doing this for save games, but not for profiles.

**Comment by Eclipse2025** [comment]
> Can you send the profile because without it, it does not do much?
[profile.zip](https://github.com/FromDarkHell/BL3SaveEditor/files/7330399/profile.zip)

sorry about that, and yes i see its closed off but still would like to see just what about the profile broke and possibly fix on my end. 
@FullZetsu thats appreciated, thanks
